### ISSUE TITLE
I don't see animation

### ISSUE THREAD

**Issue by Samn100** [MatyrobbrtMods/EatingAnimationForge#1] opened 2022-01-28 12:07 UTC
Downloaded mod for 1.16.5  and I am using forge 36.2.20 and Optifine 1.16.5 HD U G8. Animations are not showed up.

**Comment by Matyrobbrt** [comment] 2022-01-28 13:50
Try removing optifine

**Comment by Samn100** [comment] 2022-01-28 14:55
I tried to remove every mod except eating animation and I still can not see the animation. But I ould still love for this mod be compatible with Optifine. I make modpack for my use and without optifine i get only 30 fps.

**Comment by Matyrobbrt** [comment] 2022-01-28 15:50
I cannot reproduce this, neither can other people. Could you elaborate? What do you (not) see exactly? Maybe even consider sharing the game logs

**Comment by Matyrobbrt** [comment] 2022-01-28 16:09
And if you can, could you join the discord server? https://discord.gg/vV25kEaWJX It will make communication easier

**Comment by Matyrobbrt** [comment] 2022-01-28 17:30
Fixed in discord, by using a resource pack.. Minecraft is weird sometimes

**Closed as completed** 2022-01-28 17:29 UTC
